title: Island Invaders
google_analytics:
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/islandinvaders/imi-invasive
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins